name: tunisian_school_doha
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  custom_clippers: ^2.0.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.1.0
  graphql_flutter: ^5.0.0
  http: ^0.13.6
  google_fonts: ^4.0.4
  flutter_device_type: ^0.4.0
  dio: ^5.1.1
  path_provider: ^2.0.5
  qr_flutter: ^4.1.0
  webview_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/imgs/

  fonts:
    - family: bahij
      fonts:
        - asset: fonts/BahijLight.ttf
    - family: bahij-bold
      fonts:
        - asset: fonts/Bahij.ttf


